spring:
  application:
    name: delivery-tracking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5434/deliverydb
    username: postgres
    password: postgres
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping:
          delivery-placed-event:com.saadeh.delivery.delivery.tracking.domain.event.DeliveryPlacedEvent,
          delivery-pickup-event:com.saadeh.delivery.delivery.tracking.domain.event.DeliveryPickUpEvent,
          delivery-fulfilled-event:com.saadeh.delivery.delivery.tracking.domain.event.DeliveryFulFilledEvent

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 2
        waitDuration: 20ms
      instances:
        Retry_CourierAPIClient_payoutCalculation:
          baseConfig: default
          maxAttempts: 3
          retryExceptions:
            - org.springframework.web.client.ResourceAccessException
          ignoreExceptions:
            - org.springframework.web.client.HttpServerErrorException
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      CircuitBreaker_CourierAPIClient_payoutCalculation:
        baseConfig: default
        waitDurationInOpenState: 5000
