server.port: 9999

spring:
  application.name: gateway
  cloud:
    gateway.server.webflux:
      routes:
        - id: delivery-tracking-route
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/deliveries/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
        - id: courier-management-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/couriers/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
