server.port: 8081
spring:
  application:
    name: courier-management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5434/courierdb
    username: postgres
    password: postgres
kafka:
  consumer:
    bootstrap-servers: localhost:9092
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    group-id: courier-management
    properties:
      # spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: 'com.saadeh.delivery'
      spring.json.type.mapping: >-
        delivery-placed:com.saadeh.delivery.courier.management.infrastructure.event.DeliveryPlacedIntegrationEvent,
        delivery-fulfilled:com.saadeh.delivery.courier.management.infrastructure.event.DeliveryFulfilledIntegrationEvent
      spring.json.use.type.headers: true  # Critical for decoding __TypeId__

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true